### ISSUE TITLE
Catalina 以降に未対応

### ISSUE THREAD

**Issue by striderkein** [greymd/osx-open-winfs#2]
Catalina 以降はルートディレクトリ `/` 配下に書き込みができなくなったため、`sudo make install` でエラーとなります。
[参考](https://stackoverflow.com/questions/58034955/read-only-file-system-when-attempting-mkdir-data-db-on-mac)

`Makefile` の修正（他？）が必要になります。

**Comment by greymd** [comment]
ありがとうございます。最近個人的に使っていなかったので全く気付きませんでした。
現状は `/mnt_openwinfs` を使うようになっているんですが、新たな場所をどうするかなかなか悩みどころです。

ホームディレクトリ以下にマウントしてもよいんですが、Finder やシェルの誤操作で消してしまいそうで怖いんですよね。。
環境変数で定義できるようにして、デフォルトは `/usr/local/mnt_openwinfs/` あたりにしておきましょうかね。。

**Comment by greymd** [comment]
Catalina 対応バージョンリリースいたしました。
https://github.com/greymd/osx-open-winfs/releases/tag/v2.0

最新の master をクローンしてお試しください。`sudo make install` で上書きされます。
手元で動作を試したので大丈夫だと思いますが、もし動作に問題があれば教えて下さいませ！
